### ISSUE TITLE
Yank and Paste don't work correctly

### ISSUE THREAD

**Issue by fengzhou0x** [jpotterm/vscode-simple-vim#2] opened 2018-05-11 06:42 UTC
`Y` and `P` don't work correctly in normal mode. It seems to be only able to yank once.

**Comment by jpotterm** [comment] 2018-05-11 15:15
Can you give more information? They seem to work for me. An example document and key sequence would be great.

**Comment by fengzhou0x** [comment] 2018-05-14 00:06
I don't remember the exact key sequence, it seems to work fine. I'll either close this issue or provide reproduction steps in a couple of days.

**Comment by jpotterm** [comment] 2018-06-11 05:35
I'm closing this because I couldn't reproduce it. If you run into this again then I'll reopen this or you can open a new issue.

**Closed by jpotterm** 2018-06-11 05:35 UTC
