### ISSUE TITLE
visual mode doesn't work

### ISSUE THREAD

**Issue by object782** [jpotterm/vscode-simple-vim#15] opened 2018-10-18 16:43 UTC
Thank you for such a nice extension.

In my case, visual mode doesn't work even I input 'v' or 'V' key.
So, Im holding 'shift' key instead of visual mode.
And if there is notification what mode right now, it would be wonderful.

Version: 1.28.2 (user setup)
Commit: 7f3ce96ff4729c91352ae6def877e59c561f4850
Date: 2018-10-17T00:23:51.859Z
Electron: 2.0.9
Chrome: 61.0.3163.100
Node.js: 8.9.3
V8: 6.1.534.41
Architecture: x64

And there is no extension related with key inputs.

**Comment by abuisman** [comment] 2020-05-23 18:50
I thought that it didn't work as well until I just thought of using hjkl to move instead of the arrow keys. For me the visual mode works in that case.

**Comment by jpotterm** [comment] 2020-09-21 17:15
@abuisman Thanks for helping @object782 hopefully solve his problem!

@object782 I can't reproduce this. Visual mode has always worked fine for me and I haven't received any other reports of it being broken in these 2 years, so I'm going to close this. I hope you're able to solve your issue and figure out how to use visual mode.

**Closed by jpotterm** 2020-09-21 17:15 UTC
