### ISSUE TITLE
cc doesn't enter insert mode

### ISSUE THREAD

**Issue by fengzhou0x** [jpotterm/vscode-simple-vim#11] opened 2018-09-03 06:39 UTC
`cc` deletes the current line, but doesn't enter into insert mode.

**Comment by fengzhou0x** [comment] 2018-09-06 01:14
Yea, this happens with all other extensions disabled.

I'm on Mac, vscode 1.27, it happened in 1.26 as well.

I have very few vscode settings, just some font settings.

It happens in .js and .ts files. I haven't tried others.

![simple vim cc](https://user-images.githubusercontent.com/291787/45129175-8b631400-b1c5-11e8-8c52-b45bbace07ef.gif)

**Comment by jpotterm** [comment] 2018-09-06 13:54
That's really weird. It looks like it's running the `dd` action and not the `cc` action. Because `cc` shouldn't delete the whole line. I'm not really sure how to debug this without being able to reproduce it. I'm on Mac using the latest VSCode also, so there shouldn't be any difference. Here's how it looks on my computer:

![test 1](https://user-images.githubusercontent.com/134310/45161446-decf6500-b1b9-11e8-9c3f-f0d1e086556e.gif)

You could try reinstalling SimpleVim and making sure your keybindings.json is empty. If you're willing to set up the development version of this extension and do to `console.log` debugging I can walk you through that, but I wouldn't blame you if you didn't want to spend time on that.

**Comment by jpotterm** [comment] 2019-03-06 22:42
I'm closing this because I can't reproduce it and no one else has confirmed that it's a problem.

**Closed by jpotterm** 2019-03-06 22:42 UTC
